load("@STM32F103//:rules.bzl", "st_binary")
load("@STM32F103//:st_tools.bzl", "st_flash", "st_debug")
load("@STM32F103//:openocd.bzl", "openocd_flash", "openocd_debug")

st_binary(
    name = "HelloWorld",
    copts = [],
    deps = [
        "//gen/Core:Core",
        "//gen/Drivers:Drivers",
    ],
    ldscript = "gen/stm32f103cbtx_flash.ld",
    startupfile = "gen/startup_stm32f103xb.s",
    visibility = ["//visibility:public"],
)

st_flash(
    name = "flash",
    binary = ":HelloWorld",
)
st_debug(name = "debug")

openocd_flash(
    name = "ocd_flash",
    binary = ":HelloWorld",
    script_files = [ "interface/stlink.cfg", "target/stm32f1x.cfg" ],
)
openocd_debug(
    name = "ocd_debug",
    script_files = [ "interface/stlink.cfg", "target/stm32f1x.cfg" ],
)
