""

bazel_dep(name = "rules_cc", version = "0.0.10")
bazel_dep(name = "platforms", version = "0.0.10")

git_override(module_name="bazel_utilities", remote="https://github.com/0-Sacha/bazel_utilities.git", commit="230196b5427877a13e38a6e9d3b5a3b336ff2480")
git_override(module_name="bazel_arm", remote="https://github.com/0-Sacha/bazel_arm.git", commit="68698fedac97fceab3d3efdf109ba9a9aa5bb8d7")
# local_path_override(module_name = "bazel_utilities", path = "../../../bazel_utilities")
# local_path_override(module_name = "bazel_arm", path = "../../../bazel_arm")

# Replace with git_override from my repo `https://github.com/0-Sacha/bazel_stm32.git`
local_path_override(module_name = "bazel_stm32", path = "../../")

bazel_dep(name = "bazel_utilities", version = "0.0.1", dev_dependency = True)
bazel_dep(name = "bazel_arm", version = "0.0.1", dev_dependency = True)
bazel_dep(name = "bazel_stm32", version = "0.0.1", dev_dependency = True)

stm32_toolchain_extension = use_extension("@bazel_stm32//:rules.bzl", "stm32_toolchain_extension", dev_dependency = True)
inject_repo(stm32_toolchain_extension, "platforms", "bazel_utilities", "bazel_arm", "bazel_stm32")
stm32_toolchain_extension.stm32_platform(
    name = "STM32F103",

    mcu = "STM32F103CBT6",
    device_group = "STM32F103xB",

    extra_mcuopts = [ "-mfloat-abi=softfp" ],
    cxxopts = [ "-std=c++20" ],
    linkopts = [
        "-lstdc++",
        "-u _printf_float",
    ],

    specs = [ "nosys" ],
)
use_repo(stm32_toolchain_extension, "STM32F103")
use_repo(stm32_toolchain_extension, "arm-none-eabi-STM32F103")
register_toolchains("@arm-none-eabi-STM32F103//:toolchain")
