"""
"""

load("@STM32F401//:rules.bzl", "st_binary")

st_binary(
    name = "HelloWorld",
    copts = [],
    deps = [
        "//Core:Core",
        "//Drivers:Drivers",
    ],
    ldscript = "STM32F401CCUx_FLASH.ld",
    startupfile = "startup_stm32f401xc.s",
    visibility = ["//visibility:public"],
)
