"""
"""

package(default_visibility = ["//visibility:public"])

constraint_setting(name = "stm32")
constraint_setting(name = "stm32_family")

constraint_value(
    name = "stm32f0",
    constraint_setting = ":stm32_family",
)
constraint_value(
    name = "stm32f1",
    constraint_setting = ":stm32_family",
)
constraint_value(
    name = "stm32f2",
    constraint_setting = ":stm32_family",
)
constraint_value(
    name = "stm32f3",
    constraint_setting = ":stm32_family",
)
constraint_value(
    name = "stm32f4",
    constraint_setting = ":stm32_family",
)
constraint_value(
    name = "stm32f7",
    constraint_setting = ":stm32_family",
)
constraint_value(
    name = "stm32h5",
    constraint_setting = ":stm32_family",
)
constraint_value(
    name = "stm32h7",
    constraint_setting = ":stm32_family",
)
