load("@STM32F401//:rules.bzl", "st_binary")
load("@STM32F401//:st_tools.bzl", "st_flash", "st_debug")
load("@STM32F401//:openocd.bzl", "openocd_flash", "openocd_debug")

st_binary(
    name = "HelloWorld",
    copts = [],
    deps = [
        "//gen/Core:Core",
        "//gen/Drivers:Drivers",
    ],
    ldscript = "gen/STM32F401CCUx_FLASH.ld",
    startupfile = "gen/startup_stm32f401xc.s",
    visibility = ["//visibility:public"],
)

st_flash(
    name = "st_flash",
    binary = ":HelloWorld",
)
st_debug(name = "st_debug")

openocd_flash(
    name = "ocd_flash",
    binary = ":HelloWorld",
    script_files = [ "interface/stlink.cfg", "target/stm32f4x.cfg" ],
)
openocd_debug(
    name = "ocd_debug",
    script_files = [ "interface/stlink.cfg", "target/stm32f4x.cfg" ],
)
